# Generated by Django 4.0.4 on 2022-05-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aadhar', '0002_personaldetails_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aadhar',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='personaldetails',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='person',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
