# Generated by Django 4.0.4 on 2022-05-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aadhar', '0003_alter_aadhar_options_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='person',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
