# Generated by Django 4.0.4 on 2022-05-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aadhar', '0006_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['user']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='address',
            order_with_respect_to=None,
        ),
    ]
